// Auto-generated by dev_deploy.sh — do not edit manually
const String kModelDownloadUrl = 'http://localhost:8888/gemma-4-E2B-it-Q4_K_M.gguf';
const String kModelFilename = 'gemma-4-E2B-it-Q4_K_M.gguf';
